//auth
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_FORGOT_PASSWORD = "USER_FORGOT_PASSWORD";
export const USER_FORGOT_PASSWORD_REQUEST = "USER_FORGOT_PASSWORD_REQUEST";
export const SET_AUTH_LOADER = "SET_AUTH_LOADER";
export const GET_MY_IP = "GET_MY_IP";
export const SET_MY_IP = "SET_MY_IP";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_ACTIVITY_TIMEOUT = "UPDATE_ACTIVITY_TIMEOUT";
export const UPDATE_LOGOUT_TIMEOUT = "UPDATE_LOGOUT_TIMEOUT";
export const UPDATE_ACTIVTITY_MODAL = "UPDATE_ACTIVTITY_MODAL";

//setting
export const UPDATE_HEADER_TITLE = "UPDATE_HEADER_TITLE";
export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";
export const UPDATE_INDEX = "UPDATE_INDEX";
export const UPDATE_CURRENT_DOC = "UPDATE_CURRENT_DOC";
export const UPDATE_REVIEW_DOC = "UPDATE_REVIEW_DOC";
export const UPDATE_REQUESTED_DOC = "UPDATE_REQUESTED_DOC";
export const UPDATE_AUTH_CHECK = "UPDATE_AUTH_CHECK";
export const UPDATE_PDF_SETTINGS = "UPDATE_PDF_SETTINGS";
export const RESET_STATE = "RESET_STATE"; //it is generic action type

//participant
export const ADD_PARTICIPANT = "ADD_PARTICIPANT";
export const ADD_PARTICIPANT_STORE = "ADD_PARTICIPANT_STORE";
export const EDIT_PARTICIPANT = "EDIT_PARTICIPANT";
export const REMOVE_PARTICIPANT = "REMOVE_PARTICIPANT";
export const UPDATE_TOTAL_PARTICIPANT = "UPDATE_TOTAL_PARTICIPANT";
export const SAVE_PARTICIPANT = "SAVE_PARTICIPANT";

//files
export const ADD_FILE = "ADD_FILE";
export const EDIT_FILE = "EDIT_FILE";
export const REMOVE_FILE = "REMOVE_FILE";
export const SET_FILES = "SET_FILES";

//elements
export const ADD_ELEMENT = "ADD_ELEMENT";
export const GET_ELEMENTS = "GET_ELEMENT_STORE";
export const EDIT_ELEMENT = "EDIT_ELEMENT";
export const REMOVE_ELEMENT = "REMOVE_ELEMENT";
export const SET_ELEMENT = "SET_ELEMENT";

//packages
export const ADD_PACKAGE = "ADD_PACKAGE";
export const ADD_PACKAGE_LOCAL = "ADD_PACKAGE_LOCAL";
export const GET_PACKAGES = "GET_PACKAGE";
export const SET_PACKAGES = "SET_PACKAGE";
export const GET_SINGLE_PACKAGES = "GET_SINGLE_PACKAGES";
export const SET_SINGLE_PACKAGES = "SET_SINGLE_PACKAGES";
export const EDIT_PACKAGE = "EDIT_PACKAGE";
export const EDIT_PACKAGE_LOCAL = "EDIT_PACKAGE_LOCAL";
export const REMOVE_PACKAGE = "REMOVE_PACKAGE";
export const REMOVE_PACKAGE_LOCAL = "REMOVE_PACKAGE_LOCAL";
export const SET_PACKAGE_LOADER = "SET_PACKAGE_LOADER";

//templates
export const ADD_TEMPLATE = "ADD_TEMPLATE";
export const ADD_TEMPLATE_LOCAL = "ADD_TEMPLATE_LOCAL";
export const GET_TEMPLATES = "GET_TEMPLATE";
export const SET_TEMPLATES = "SET_TEMPLATE";
export const GET_SINGLE_TEMPLATES = "GET_SINGLE_TEMPLATES";
export const SET_SINGLE_TEMPLATES = "SET_SINGLE_TEMPLATES";
export const EDIT_TEMPLATE = "EDIT_TEMPLATE";
export const EDIT_TEMPLATE_LOCAL = "EDIT_TEMPLATE_LOCAL";
export const REMOVE_TEMPLATE = "REMOVE_TEMPLATE";
export const REMOVE_TEMPLATE_LOCAL = "REMOVE_TEMPLATE_LOCAL";
export const SET_TEMPLATE_LOADER = "SET_TEMPLATE_LOADER";
export const GET_CATAGORIES = "GET_CATAGORIES";
export const SET_CATAGORIES = "SET_CATAGORIES";

//forms
export const ADD_FORM = "ADD_FORM";
export const ADD_FORM_LOCAL = "ADD_FORM_LOCAL";
export const GET_FORMS = "GET_FORM";
export const SET_FORMS = "SET_FORM";
export const GET_SINGLE_FORMS = "GET_SINGLE_FORMS";
export const SET_SINGLE_FORMS = "SET_SINGLE_FORMS";
export const EDIT_FORM = "EDIT_FORM";
export const EDIT_FORM_LOCAL = "EDIT_FORM_LOCAL";
export const REMOVE_FORM = "REMOVE_FORM";
export const REMOVE_FORM_LOCAL = "REMOVE_FORM_LOCAL";
export const SET_FORM_LOADER = "SET_FORM_LOADER";
export const SAVE_INDEXES = "SAVE_INDEXES";

//sharing
export const ADD_SHARING = "ADD_SHARING";
export const ADD_SHARING_LOCAL = "ADD_SHARING_LOCAL";
export const GET_SHARINGS = "GET_SHARING";
export const SET_SHARINGS = "SET_SHARING";
export const GET_SINGLE_SHARINGS = "GET_SINGLE_SHARINGS";
export const SET_SINGLE_SHARINGS = "SET_SINGLE_SHARINGS";
export const EDIT_SHARING = "EDIT_SHARING";
export const EDIT_SHARING_LOCAL = "EDIT_SHARING_LOCAL";
export const REMOVE_SHARING = "REMOVE_SHARING";
export const REMOVE_SHARING_LOCAL = "REMOVE_SHARING_LOCAL";
export const SET_SHARING_LOADER = "SET_SHARING_LOADER";
export const SAVE_SHARINGS = "SAVE_SHARINGS";
export const SAVE_REVIEW_USER = "SAVE_REVIEW_USER";
export const SAVE_REQUEST_USER = "SAVE_REQUEST_USER";
